### ISSUE TITLE
bug: when building docs, reports error.

### ISSUE THREAD

**Issue by EliazTray** [xiguaxigua/vuepress-plugin-demo-block#5]
![image](https://user-images.githubusercontent.com/16015431/50626587-05d05480-0f6a-11e9-9be3-c9222efa3e4e.png)

As shown above, it may look like need to do some compatibility processing.

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/50638441-bead8800-0f98-11e9-8d48-753c4cd32bbf.png)

I did not reproduce this problem locally. Maybe you need to use the new `vuepress` version.

**Comment by EliazTray** [comment]
@xiguaxigua 👌
